### ISSUE TITLE
What's your favorite gif?

### ISSUE THREAD

**Issue by arthurvr** [wbinnssmith/ama#2]

**Comment by wbinnssmith** [comment]
Our HipChat instance at work crammed this into an emoticon, and I've fallen in love with it ever since:

![](http://awesomegifs.com/wp-content/uploads/big-red-nope-button.gif)

Also recently @sindresorhus introduced me to this one. It is programming distilled into a gif:

![](https://cloud.githubusercontent.com/assets/170270/9568930/cf64015c-4f83-11e5-985b-c766a2057dc7.gif)

And my girlfriend inexplicably laughs EVERY SINGLE TIME at this one, which warms my heart:

![](http://awesomegifs.com/wp-content/uploads/psycho-potter-taco-fling.gif)
