### ISSUE TITLE
How did you get into programming?

### ISSUE THREAD

**Issue by sindresorhus** [wbinnssmith/ama#8]

**Comment by wbinnssmith** [comment]
Honestly I'm not one of those folks who was writing BASIC in the womb or anything. I've just really, really been into computers since my late father brought me up with technology in my life. I was one of those kids who tried a different Linux distribution on a weekly basis throughout high school, doing stage 1 Gentoo installs and compiling things from scratch and all that. Breaking things and putting them back together again was a serious pastime of mine.

When I came to undergrad CS seemed like a perfect fit even though I hadn't written a line of serious code in my life. I ended up falling in love with programming since I could actual _build_ the things I grew up using, albeit at a slow pace initially (and today still :wink:). Found GitHub in my later college years, which made complete sense growing up in the OSS world. Now I have the privilege to work on a similar product at Bitbucket, and have come to appreciate the strengths and weaknesses of both.
